// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7PtCco7IN2yminv1xivRL790YrIZDMFk',
    appId: '1:167116244714:web:5537af81cd8cfcd9a93993',
    messagingSenderId: '167116244714',
    projectId: 'ticketchain-k',
    authDomain: 'ticketchain-k.firebaseapp.com',
    storageBucket: 'ticketchain-k.appspot.com',
    measurementId: 'G-NSPBW3RDFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl-VLlPsAyWlvTC_yPuV2H3KHA-Ir-iOY',
    appId: '1:167116244714:android:4fddb2a9642d2ceea93993',
    messagingSenderId: '167116244714',
    projectId: 'ticketchain-k',
    storageBucket: 'ticketchain-k.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzpx5eNXxosoFftXCBrAtlPuDyRZ6gyXE',
    appId: '1:167116244714:ios:2cdfe3917e0d3170a93993',
    messagingSenderId: '167116244714',
    projectId: 'ticketchain-k',
    storageBucket: 'ticketchain-k.appspot.com',
    iosClientId:
        '167116244714-enu95e1u78tfekomn9qq21uk6qi75sfu.apps.googleusercontent.com',
    iosBundleId: 'com.krfld.ticketchain',
  );
}
